/**
 * Route table — auto-derived from the screens on the canvas. Each screen
 * contributes a route: path = slugified screen name, destination = the
 * screen's id. Screens importing from `./routes.js` can resolve `/profile`
 * back to a screen id; the canvas's nav-intercept uses the same mapping
 * to pan the camera to the target screen when a user clicks a <Link>.
 *
 * Unlike the other stores, this one does NOT persist to localStorage — the
 * authoritative source is the tldraw document itself. We rebuild the table
 * whenever the screen inventory changes (see TldrawCanvas listener).
 */

export type Route = {
  id: string; // screen id
  name: string; // screen display name
  path: string; // always starts with "/"
};

type Listener = (routes: Route[]) => void;

class RouteTableStore {
  private current: Route[] = [];
  private listeners = new Set<Listener>();

  get(): Route[] {
    return this.current;
  }

  /** Replace the full route table; called whenever screens change. */
  setRoutes(routes: Route[]) {
    // Quick equality check — avoid notifying if nothing changed.
    if (
      routes.length === this.current.length &&
      routes.every((r, i) => {
        const prev = this.current[i];
        return prev?.id === r.id && prev?.name === r.name && prev?.path === r.path;
      })
    ) {
      return;
    }
    this.current = routes;
    for (const l of this.listeners) l(routes);
  }

  /** Find a route by path (with or without leading slash). */
  findByPath(to: string): Route | null {
    if (!to) return null;
    const norm = to.startsWith("/") ? to : "/" + to;
    const lower = norm.toLowerCase();
    return (
      this.current.find((r) => r.path.toLowerCase() === lower) ?? null
    );
  }

  subscribe(l: Listener): () => void {
    this.listeners.add(l);
    return () => {
      this.listeners.delete(l);
    };
  }

  toRoutesJs(): string {
    const entries = this.current
      .map(
        (r) =>
          `  { id: ${JSON.stringify(r.id)}, name: ${JSON.stringify(r.name)}, path: ${JSON.stringify(r.path)} }`,
      )
      .join(",\n");
    return `/** Auto-generated route table. Paths map to screens on the canvas.
 *  Do NOT edit this file directly — it is regenerated whenever the screen
 *  inventory changes. Rename a screen on the canvas to rename its route. */

export const ROUTES = [
${entries}
];

export function findRouteByPath(to) {
  if (!to) return null;
  const norm = to.startsWith('/') ? to : '/' + to;
  const lower = norm.toLowerCase();
  return ROUTES.find((r) => r.path.toLowerCase() === lower) ?? null;
}
`;
  }

  toPromptDescription(): string {
    if (this.current.length === 0) return "";
    const lines = ["Routes available for navigation:"];
    for (const r of this.current) {
      lines.push(`- "${r.name}" → path: ${r.path}`);
    }
    return lines.join("\n");
  }
}

export const routeTableStore = new RouteTableStore();

export function nameToPath(name: string): string {
  const slug = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (!slug) return "/";
  if (slug === "home" || slug === "index" || slug === "root") return "/";
  return "/" + slug;
}

if (typeof window !== "undefined") {
  (
    window as unknown as { __routeTableStore: RouteTableStore }
  ).__routeTableStore = routeTableStore;
}
